# Generated by Django 3.1.3 on 2020-12-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songsData', '0001_initial'),
        ('userFlagData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikedlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergenereflags',
            name='genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsData.genere'),
        ),
        migrations.AddField(
            model_name='usergenereflags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userartistflag',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsData.artist'),
        ),
        migrations.AddField(
            model_name='userartistflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
