# Generated by Django 3.1.3 on 2020-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userFlagData', '0002_auto_20201206_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartistflag',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usergenereflags',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
