# Generated by Django 3.1.3 on 2020-12-03 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('genere', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsData.artist')),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsData.genere')),
            ],
        ),
    ]
