# Generated by Django 3.1.3 on 2020-12-06 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songsData', '0002_auto_20201206_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genere',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
