# Generated by Django 3.1.3 on 2020-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsData', '0003_auto_20201207_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
