name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello there, Thanks for raising this issue!'' first issue'
        pr-message: 'Hi, Welcome to this repo!'' first pr'
